# Generated by Django 4.2.1 on 2023-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecoweb',
            name='validacao',
            field=models.BooleanField(default=False),
        ),
    ]
