# Generated by Django 4.2.1 on 2023-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_enderecoweb_validacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoweb',
            name='validacao',
            field=models.CharField(default='⚪', max_length=2),
        ),
    ]
